### ISSUE TITLE
PNG encoder throws an exception on x64

### ISSUE THREAD

**Issue by hishamco** [SixLabors/ImageSharp#1228]
Seems there's a lake on supporting this on 64 bit, for more details, please refer to https://github.com/OrchardCMS/OrchardCore/issues/6414

**Comment by antonfirsov** [comment]
@hishamco to make it actionable for us, can you please:
1. Fill the issue template, making sure you include:
  - The exact type of your CPU
  - .NET Core version
  - OS version
2. Provide the PNG you are trying to resize. Note: based on stack trace, the issue is in the PNG encoder.

**Comment by ArieGato** [comment]
### Steps to Reproduce
fire the following request to OrchardCore: https://my.domain/media/myimage.png?width=100

### System Configuration

- ImageSharp version:
SixLabors.ImageSharp 1.0.0-rc0002

- Other ImageSharp packages and versions:
SixLabors.ImageSharp.Web 1.0.0-rc0003

- Environment (Operating system, version and so on):

Published the web site in devops
```
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CmsWeb.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory) -r win-x64 --self-contained'
```

windows server 64 bit.
.net core 3.1.5

It fails for all the png files I tested, but here's an example.
![digid](https://user-images.githubusercontent.com/1059562/84655304-06b43680-af11-11ea-840f-a36690006566.png)
